# font settings
font_family Liga SFMono Nerd Font Regular
italic_font Liga SFMono Nerd Font Regular Italic
bold_font Liga SFMono Nerd Font Medium
bold_italic_font SFMono Nerd Font Medium Italic
disable_ligatures always
font_size 18.0

# cursor settings
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

# bell settings
enable_audio_bell no
visual_bell_duration 0.0
visual_bell_color none

# title bar settings
macos_titlebar_color background

# tab bar settings
tab_bar_style hidden

# text mappings
map alt+backspace send_text all \x17
map super+backspace send_text all \x15
map super+left send_text all \x01
map super+right send_text all \x05
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# tab mappings
map cmd+t new_tab
map shift+cmd+t close_tab
map shift+alt+l next_tab
map shift+alt+h previous_tab
map shift+alt+tab select_tab

# window mappings
map cmd+w new_window
map shift+cmd+w close_window
map alt+l next_window
map alt+h previous_window
map alt+tab focus_visible_window

# layouts mappings
enabled_layouts horizontal, vertical
map cmd+shift+v goto_layout vertical
map cmd+shift+h goto_layout horizontal

# others
sync_to_monitor no

# theme
include themes/tokyonight-night.conf
